### ISSUE TITLE
aisradar  source repos has no site.yml   why not change the source?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#49]
$ check-sources
==== Building plugins/sources/admiralty_tide_tables_pi/manual/site.yml
No manual/site.yml found in plugins/sources/aisradar_pi
==== Building plugins/sources/autopilot_route_pi/manual/site.yml

**Comment by leamas** [comment]
We are basically just waitign for https://github.com/Verezano/AISradar_pi/pull/20 to be accepted. 

If this takes too long time we could of course make a PR to Pavel's repo, which is the one we are using now. But we as well just wait a little, something things like these needs a little time.

Just to be clear: IMHO these kind of problems are not blocking, we will probably have to live with them to some extent. The manual is reasonably OK  anyway

**Comment by rgleason** [comment]
Good, lets wait.  I wrote him recently.

**Comment by leamas** [comment]
I have listed this in #23, so we can close this bug. 

Next time you write to maintainers about the need accept PR, please consider some notes.

  - Be a little polite, ask for a decision to reject or accept the PR rather than just "we need this PR merged".
  - Be accurate. A non-accepted PR does not stop from having the manual, it's just that we don't want  to maintain a fork.
  - Be kind and submit the link it's about, so maintainer just has to click on the link in the email to get there.
  - EDIT: Of course, the PR also needs to be sane, have a proper description and readable commits. You can see the differences between https://github.com/Verezano/AISradar_pi/pull/20 and https://github.com/Verezano/AISradar_pi/pull/19

**Comment by rgleason** [comment]
Good point, my email was polite.
