### ISSUE TITLE
checked out to previous commit to avoid windvane error

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#56]
/source.state.sh restore
What does this mean at the end?
Did it download ok?
Should I run  restore again?

```
Resolving deltas: 100% (6/6), done.
fatal: invalid refspec '44e8b986e423d7033d83b40a9ff7b0f40f205768?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git

```

```
Restoring into weather_routing_pi
Cloning into 'weather_routing_pi'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 63 (delta 2), reused 39 (delta 0), pack-reused 0 eceiving objects:  23% (15/63)
Receiving objects: 100% (63/63), 32.30 KiB | 3.59 MiB/s, done.
Resolving deltas: 100% (2/2), done.
...
Resolving deltas: 100% (6/6), done.
Updating files: 100% (87/87), done.
fatal: invalid refspec 'a9fd552580fd56b8b9a67f2b5866728c3a264ec3?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
Restoring into windvane_pi
Cloning into 'windvane_pi'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (61/61), done.
Receiving obj 79 (delta 0), reused 68 (delta 0), pack-reused 0 eceiving objects:  53% (42/79)
Receiving objects: 100% (79/79), 20.42 KiB | 2.27 MiB/s, done.
...
Receiving objects: 100% (30/30), 151.20 KiB | 1.70 MiB/s, done.
Resolving deltas: 100% (6/6), done.
fatal: invalid refspec '44e8b986e423d7033d83b40a9ff7b0f40f205768?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
```

**Comment by rgleason** [comment]
See notes at   https://github.com/opencpn-manuals/plugins/commit/5c3b0a058d8d72048a5709dc604fb7661c436464

Have tried 3 times to fix this.

**Comment by Rasbats** [comment]
GPS-Odometer URL incorrect - used opencpn-manuals fork. Now fixed.

**Comment by rgleason** [comment]
Very frustrating. How would i know that? Every time I try to do something, there is some different problem i did not create.

**Comment by Rasbats** [comment]
Like Jon I prefer a git gui, in my case Github Desktop. Using this I can do a quick pull to make sure the files on my PC are the latest. There are times when it has caused me problems but very few and far between.

**Comment by rgleason** [comment]
I may try using git gui. I have it but use cli mostly, and alec wants us to use old git commands.

**Comment by leamas** [comment]
> Like Jon I prefer a git gui, in my case Github Desktop. Using this I can do a quick pull to make sure the files on my PC are the latest. 

_git pull_ is problematic since it has a tendency to get into a bad state when it fails (which is not uncommon with many devs active). _git rebase_ basically does the same thing, but has the really nice fallback _git rebase --abort_ which makes it possible to review possible errors without a broken main branch

**Comment by leamas** [comment]
The git CLI commands are certainly not "old". On  the contrary, Mike and I have already run into troubles because the GUI does not support the latest git functionality which we use. The Github GUI is BTW not the first attempt to create a useful GUI for git. These attempts regularly fails over time.

Of course, using a GUI for everyday tasks might be useful if one is used to these kind of tools. However, we need to also use the CLI commands in many situations:
 
  - No GUI makes it possible to handle the complete git CLI functionality. I presume the the Github GUI supports using rebase instead of pull/merge, though. 
  - When I or someone else needs to describe what someone should do, the CLI commands are so much easier to write and use compared to screen dumps from a GUI.
  - When searching help from me or on the web, there will be basically zero hits on how to fill in the Github GUI, but tons of solutions using the CLI

**Comment by rgleason** [comment]
I have copied both of your posts to my cheat sheet.  I wholeheartedly agree with Alecs last two points, b
