### ISSUE TITLE
After push -f origin main:build

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#70]
The link to built html docs here

https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html

Does not show the changes and commits that were pushed!!!
Why?  Because it is building the Branch : Main.

We should have a way to look at IO that builds the Branch: Build!! 
Otherwise the changes will not show up and there will be no way to check things.

This did checkout https://github.com/opencpn-manuals/plugins/runs/3654494793 ok, , but there is no way to look at the doc html output    (Note I did do antora site.yml  locally and reviewed extensively so that should be acceptable)

I just wanted to be clear about expectations here.

The   https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html
does not show antora site.yml   html from the BUILD branch!!!  

That should be made clearer in the Workflow I think.

**Comment by rgleason** [comment]
I think we should be looking at the gh-pages branch perhaps?

**Comment by leamas** [comment]
No, this should be closed since you **still** not provides the commit. How do you expect anyone could do anything about these issues if you don't specify what commit you have pushed?

**Comment by leamas** [comment]
Good night.

**Comment by rgleason** [comment]
Very sorry Alec  I guess I need it every time

**This is the from BUILD Branch**
 2254bf95549ca4e9653a0ac7356bdfca50711935

**Comment by leamas** [comment]
OK, we are talking about 2254bf9. When you have a commit hash like this, it's defined on its own, be it in the build branch or not,

I can see how it looks using `git show 2254bf9`.   At the very top I see this:

```
--- a/manual/master-plugins/modules/ROOT/nav.adoc
+++ b/manual/master-plugins/modules/ROOT/nav.adoc
@@ -3,7 +3,7 @@
 * General
 ** xref:opencpn-plugins:misc:terminology.adoc[Terminology]
 ** xref:opencpn-plugins:misc:plugin-install.adoc[Plugin Installation]
-** xref:opencpn-plugins:misc:draw-messaging.adoc[OCPN Draw Messaging]
+** xref:opencpn-plugins:misc:draw-messaging.adoc[Draw Messaging]
```

I can push it to the build branch using `git push -f origin 2254bf9:build`. This is identical to what you did (or thought you did)

I can see it building at https://github.com/opencpn-manuals/plugins/actions/runs/1256629691 (that is, the top-most entry under the Actions button). Need to wait 3-4 minutes until job completes

I can see that site is published under [Settings | Pages](https://github.com/opencpn-manuals/plugins/settings/pages) - occasionally there is a short (some seconds) delay here.

In https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html I can now see the left navigation pane, under General which has _Draw Messaging_ rather than _OCPN Draw Messaging_.

Ergo: everything works as expected.

Note: As soon as for example Mike makes a new push to build, the changes might be lost. However, after  that you push to main (and Mike rebases his local branch) they will reappear. You can check if someone has pushed a  new build on top of your using:
    
    $ git remote update origin
    $ git rev-parse --short origin/build
    2254bf9

Here, the build branch is still at `2254bf9`. If/when Mike or I pushes a new commit to _build_, the reported hash will change.

**Comment by rgleason** [comment]
Thank you for the great explanation.  So, the html pages **are** the most current push. Very interesting use of git.  Can we make a How To?  How to use the html?  or something?

https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/index.html

**Comment by leamas** [comment]
IMHO, this should be closed.
