### ISSUE TITLE
Full Linkcheck   not working?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#71]
I tried two empty [full-linkcheck]  and git push origin main:main  and nothing seems to happen. Also it does not show up in some views.

**Comment by leamas** [comment]
Same here. When will you start providing the commits you have pushed?  What is the problem?

**Comment by Rasbats** [comment]
empty [full-linkcheck] and git push -f origin main:build works for me.

**Comment by rgleason** [comment]
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git log --oneline -10
ff04b07 (HEAD -> main, origin/main, origin/HEAD) [full-linkcheck] empty commit    <--- HERE 
d47ac45 [full-linkcheck] empty commit <---HERE
2254bf9 sml edit nav plugins nav-plugins adoc   
0bc313f edit workflows table
0fbaf22 [full-linkcheck] empty commit
5bfbe89 Rm iacfleet
8576fd5 Revert"Update index.adoc", a silly test commit.
5e25a63 Update index.adoc
d59523b Update author.adoc
1aedc8f Update author.adoc

**Comment by rgleason** [comment]
Oh you do the linkcheck on the BUILD branch always?  Not on Main?
Had forgotten that.

**Comment by rgleason** [comment]
Did not push it to build    Sorry

**Comment by rgleason** [comment]
Well actually I have pushed to main before and it worked.  So I am missing something here
Here I pushed to Main

https://github.com/opencpn-manuals/plugins/commit/33be3a124d62aeb4eaa13bcffae0632eb6f15ce8

**Comment by rgleason** [comment]
Mike's full-linkcheck on   the build branch
685c563ad41a3b907778880b97da3fe04effac5f

Does not seem to be completing either.  I had that problem too.

**Comment by Rasbats** [comment]
@rgleason : Have a look in "actions".

**Comment by leamas** [comment]
That is, in https://github.com/opencpn-manuals/plugins/runs/3655843555. An indeed, the full-linkcheck fails.

Using `git blame` (undisclosed details) we need to investigate c044b755. Here we have:

```
        --exclude ephemeris.com \
        --exclude clearskyinstitute.com \
     --exclude forum.openmarine.net     \
+       --exclude techsail.com 

```
Conclusions:
  - This looks like crap. Please respect indentation so we get readable files.
  - The added line misses it's trailing '\\', that's why the check fails
  - The line contains trailing whitespace (horrors!). Please activate the standard pre-commit hook to avoid this
  - This commit should never had been pushed to main, since the test run when pushing to build obviously failed.
  - The commit description is not that enlightening. Something like _w3c-linkcheck: Exclude techsail.com_ or so would perhaps be better.

**Comment by leamas** [comment]
I think we could live without working [full-linkcheck] for a while until Rick fixes this. If it becomes a problem, it's otherwise easy to fix.

**Comment by leamas** [comment]
@rgleason : This is your desk...

**Comment by rgleason** [comment]
Will do, sorry.

**Comment by rgleason** [comment]
fixed

**Comment by leamas** [comment]
Right. Final notes:
  - When fixing an issue like this, adding `(#71)` to the commit description provides valuable linking to the issue.
  - Originally, the excludes were ordered so it should be easier to look for specific items. I have restored the ordering in 25ea807

**Comment by rgleason** [comment]
https://github.com/opencpn-manuals/plugins/commit/59e65ed9f48768ad5b948b093208bf2765631651
